### ISSUE TITLE
template settings color picker

### ISSUE THREAD

**Issue by Sylensky** [TeemoCell/NamelessMC-Template-Noir#2]
Not sure if this is really related to this but iam keeping it tracked nonetheless:
In some template settings it is not visible which color was picked from the color picker. for example:
![image](https://user-images.githubusercontent.com/57076968/158465874-349e2165-b7b9-4cc4-b889-e3ddf24391e0.png)

**Comment by TeemoCell** [comment]
I guess you mean template settings from a other template like Cobalt?

**Comment by Sylensky** [comment]
yes thats what i meant

**Comment by TeemoCell** [comment]
The problem is that i don't have any of the paid template. So i can't really edit the template settings. I dmed already one dev but never got a response. I don't really want to spend 30-50€ to buy all paid template which i never use.

**Comment by Sylensky** [comment]
i own some - might give it a deeper look later on.

**Comment by Sylensky** [comment]
lets keep this issue open as a reminder.

**Comment by KaspianDev** [comment]
> Not sure if this is really related to this but iam keeping it tracked nonetheless: In some template settings it is not visible which color was picked from the color picker. for example: ![image](https://user-images.githubusercontent.com/57076968/158465874-349e2165-b7b9-4cc4-b889-e3ddf24391e0.png)

futurioom

**Comment by TeemoCell** [comment]
I got the template now, thx to @KaspianDev . Will add support for the template soon.
